config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
    resources :books
  patch 'books/:id' => 'books#update', as: 'update_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

 # def create
#     @book = Book.new(book_params)
#    if @book.save
 #     redirect_to book_path(@book.id)
#    else
#      @books = Book.all
#      render :index
#    end
#  end
  
  def create
     @book = Book.new(book_params)
     if @book.save
        redirect_to book_path(@book.id), notice: 'successfully'
     else
        flash.now[:alert] = 'メッセージを入力してください。'
        @books = Book.all
        render :index
     end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def destroy
    book = Book.find(params[:id]) 
    book.destroy
    redirect_to '/books'  
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id), notice: 'successfully'
   else
     render :edit
   end 
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end 
end
  

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<html><head><style type="text/css">.turbolinks-progress-bar {
  position: fixed;
  display: block;
  top: 0;
  left: 0;
  height: 3px;
  background: #0076ff;
  z-index: 9999;
  transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
  transform: translate3d(0, 0, 0);
}</style>
    
    
  <body>
    <% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
    
    <h1>Editing Book</h1>
  <%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<p>
  <strong>Title:</strong>
</p>
  <%= f.text_field :title %>
<p>
  <strong>Body:</strong>
</p>
  <%= f.text_area :body %>
  
  <%= f.submit 'Update Book' %>
  
<% end %>
<td><%= link_to "Show", "/books/#{@book.id}" %></td>
<td><%= link_to "Back", books_path %></td>

</body></html>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>
  

<% @books.each do |book| %>
<tr>
  <td><%= book.title %></td>
  <td><%= book.body %></td>
  <td><%= link_to "Show", "/books/#{book.id}" %></td>
  <td><%= link_to "Edit", edit_book_path(book.id) %></td>
  <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
</tr>

  
<% end %>
</table>



<h1>New Books</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
<div class="field">
    <label for="book_title">Title</label>
    <input class="book_title" type="text" name="book[title]" id="book_title">
  </div>
  
	<div class="field">
    <label for="book_body">Body</label>
    <textarea class="book_body" name="book[body]" id="book_body"></textarea>
  </div>
  
  <div class="actions">
    <input type="submit" name="commit" value="Create Book" data-disable-with="Create Book">
  </div>

<% end %>

app/views/books/new.html.erb
<h1>新規投稿</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<style type="text/css">.turbolinks-progress-bar {
  position: fixed;
  display: block;
  top: 0;
  left: 0;
  height: 3px;
  background: #0076ff;
  z-index: 9999;
  transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
  transform: translate3d(0, 0, 0);
}</style>
<body>
<p id="notice"></p>

<p>
  <strong>Title:</strong>
</p>
<%= @book.title %>


<p>
  <strong>Body:</strong>
</p>
<%= @book.body %>



<%= link_to "Edit", edit_book_path(@book.id) %>
<a class="back" href="/books">Back</a>
</body>

app/views/homes/top.html.erb
<link rel="stylesheet" href="top.html.css" >
    <h1>
      ようこそ
      <strong>Bookers</strong>
      へ！
    </h1>
    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>
    <p>
      <a><%= link_to "start", books_path %></a>
    </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <div class="text-success">
     <%= flash[:notice] %>
    </div>
    <div class="text-danger">
     <%= flash[:alret] %>
    </div>
     </div>
  </head>
        <%= yield %>
</html>